// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwlzgthizqziebmqqief.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3bHpndGhpenF6aWVibXFxaWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTU5ODMsImV4cCI6MjA2MjkzMTk4M30.HGVbl5filEdVhGssy2JDbysibfl1uReguzIK6VwgNog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);